source 'https://rubygems.org'
ruby '2.0.0'

gem 'sinatra', :require => 'sinatra/base'
gem 'unicorn'
gem 'erubis'
gem 'builder'
gem 'i18n', '~> 0.6.9'
gem 'activesupport', '~> 4.1.1'
gem 'nokogiri'
gem 'nestful', '1.0.2'
gem 'bcrypt-ruby'
gem 'rack-ssl'
gem 'omniauth-twitter'
gem 'omniauth-github'
gem 'rake'
gem 'rdiscount'
gem 'mail'
gem 'twitter'
gem 'closure-compiler'
gem 'yui-compressor'
gem 'dedent'
gem 'dalli'
gem 'memcachier'
gem 'sanitize'
gem 'redis'
gem 'gibbon', :git => 'https://github.com/amro/gibbon.git'
gem 'dotenv'

group :development do
  gem 'thin'
  gem 'debugger'
end

# DB
gem 'sequel'
gem 'sinatra-sequel'
gem 'sequel_postgresql_triggers'
gem 'pg'

# Assets
gem 'sprockets'
gem 'sprockets-commonjs', '0.0.6'
gem 'uglifier'
gem 'coffee-script'
gem 'stylus'
gem 'stylus-source', '0.31.0'
gem 'eco'
gem 'json', '~> 1.7.7'
gem 'cft-source', '>= 0.0.6'
